ALTER TABLE PARAGRAPH ADD numberDetail VARCHAR(100) NULL;

ALTER TABLE SYSTEMUSER ADD assistant INT NULL;
ALTER TABLE SYSTEMUSER ADD translator INT NULL;
UPDATE SYSTEMUSER SET assistant = 0, translator = 0;
COMMIT;


ALTER TABLE OBSERVATION ADD portuguesTranslation INT NULL;
UPDATE OBSERVATION SET portuguesTranslation = 0;
COMMIT;