/*
Marcos Godoy
*/

CKEDITOR.plugins.add( 'simonflags',
{
	requires : [ 'dialog' ],

	init : function( editor )
	{
		editor.config.simonflags_path = editor.config.simonflags_path || ( this.path + 'images/' );
		editor.addCommand( 'simonflags', new CKEDITOR.dialogCommand( 'simonflags' ) );
		editor.ui.addButton( 'simonflags',
			{
				label : 'Banderas',
				command : 'simonflags',
				icon: this.path + 'images/flag.gif'

			});
		CKEDITOR.dialog.add( 'simonflags', this.path + 'dialogs/simonflags.js' );
	}
} );

/**
 * The base path used to build the URL for the smiley images. It must end with
 * a slash.
 * @name CKEDITOR.config.simonflags_path
 * @type String
 * @default {@link CKEDITOR.basePath} + 'plugins/smiley/images/'
 * @example
 * config.simonflags_path = 'http://www.example.com/images/smileys/';
 * @example
 * config.simonflags_path = '/images/smileys/';
 */

/**
 * The file names for the smileys to be displayed. These files must be
 * contained inside the URL path defined with the
 * {@link CKEDITOR.config.simonflags_path} setting.
 * @type Array
 * @default (see example)
 * @example
 * // This is actually the default value.
 * config.simonflags_images = [
 *     'regular_smile.gif','sad_smile.gif','wink_smile.gif','teeth_smile.gif','confused_smile.gif','tounge_smile.gif',
 *     'embaressed_smile.gif','omg_smile.gif','whatchutalkingabout_smile.gif','angry_smile.gif','angel_smile.gif','shades_smile.gif',
 *     'devil_smile.gif','cry_smile.gif','lightbulb.gif','thumbs_down.gif','thumbs_up.gif','heart.gif',
 *     'broken_heart.gif','kiss.gif','envelope.gif'];
 */
CKEDITOR.config.simonflags_images = [
	'andorra.png','argentina.png','bolivia.png','brasil.png','chile.png','colombia.png','costarica.png','cuba.png','dominicana.png','ecuadr.png','elsalvador.png','espana.png','guatemala.png','honduras.png','mexico.png','nicaragua.png','nicaragua.png','paraguay.png','peru.png','portugal.png','uruguay.png','venezuela.png'];
/**
 * The description to be used for each of the smileys defined in the
 * {@link CKEDITOR.config.simonflags_images} setting. Each entry in this array list
 * must match its relative pair in the {@link CKEDITOR.config.simonflags_images}
 * setting.
 * @type Array
 * @default  The textual descriptions of smiley.
 * @example
 * // Default settings.
 * config.simonflags_descriptions =
 *     [
 *         'simonflags', 'sad', 'wink', 'laugh', 'frown', 'cheeky', 'blush', 'surprise',
 *         'indecision', 'angry', 'angel', 'cool', 'devil', 'crying', 'enlightened', 'no',
 *         'yes', 'heart', 'broken heart', 'kiss', 'mail'
 *     ];
 * @example
 * // Use textual emoticons as description.
 * config.simonflags_descriptions =
 *     [
 *         ':)', ':(', ';)', ':D', ':/', ':P', ':*)', ':-o',
 *         ':|', '>:(', 'o:)', '8-)', '>:-)', ';(', '', '', '',
 *         '', '', ':-*', ''
 *     ];
 */
CKEDITOR.config.simonflags_descriptions =
	[
		'ANDORRA','ARGENTINA','BOLIVIA','BRASIL','CHILE','COLOMBIA','COSTARICA','CUBA','DOMINICANA','ECUADR','ELSALVADOR','ESPANA','GUATEMALA','HONDURAS','MEXICO','NICARAGUA','NICARAGUA','PARAGUAY','PERU','PORTUGAL','URUGUAY','VENEZUELA'
	];

/**
 * The number of columns to be generated by the smilies matrix.
 * @name CKEDITOR.config.simonflags_columns
 * @type Number
 * @default 8
 * @since 3.3.2
 * @example
 * config.simonflags_columns = 6;
 */
